"""Tests for deterministic rule evaluation."""

from __future__ import annotations

from context_audit.models import ContextCategory, FileInfo
from context_audit.rules import evaluate_rules


def test_clean_source_file_not_unnecessary():
    info = FileInfo(
        path="/project/src/main.py",
        relative_path="src/main.py",
        extension=".py",
        size_bytes=1000,
        char_count=1000,
        line_count=40,
        estimated_tokens=250,
    )
    matches = evaluate_rules(info, "def main():\n    print('hello')\n")
    assert len(matches) == 0
    assert not any(m.is_unnecessary for m in matches)


def test_vendor_directory_rule():
    info = FileInfo(
        path="/project/node_modules/lodash/index.js",
        relative_path="node_modules/lodash/index.js",
        extension=".js",
        size_bytes=5000,
        char_count=5000,
        line_count=150,
        estimated_tokens=1250,
    )
    matches = evaluate_rules(info)
    assert any(m.category == ContextCategory.VENDOR for m in matches)
    assert any(m.is_unnecessary for m in matches)


def test_build_directory_rule():
    info = FileInfo(
        path="/project/dist/bundle.js",
        relative_path="dist/bundle.js",
        extension=".js",
        size_bytes=20000,
        char_count=20000,
        line_count=1,
        estimated_tokens=5000,
    )
    matches = evaluate_rules(info)
    assert any(m.category == ContextCategory.BUILD_ARTIFACT for m in matches)


def test_lockfile_rule():
    lockfiles = ["package-lock.json", "poetry.lock", "Cargo.lock", "pnpm-lock.yaml", "go.sum"]
    for lockfile_name in lockfiles:
        info = FileInfo(
            path=f"/project/{lockfile_name}",
            relative_path=lockfile_name,
            extension=f".{lockfile_name.split('.')[-1]}",
            size_bytes=15000,
            char_count=15000,
            line_count=400,
            estimated_tokens=3750,
        )
        matches = evaluate_rules(info)
        assert any(m.category == ContextCategory.LOCKFILE for m in matches), (
            f"Failed for {lockfile_name}"
        )


def test_generated_filename_rule():
    generated_names = [
        "api.pb.go",
        "service_pb2.py",
        "schema.generated.ts",
        "model.g.dart",
        "app.min.js",
        "bundle.js.map",
    ]
    for gen_name in generated_names:
        info = FileInfo(
            path=f"/project/src/{gen_name}",
            relative_path=f"src/{gen_name}",
            extension=f".{gen_name.split('.')[-1]}",
            size_bytes=4000,
            char_count=4000,
            line_count=100,
            estimated_tokens=1000,
        )
        matches = evaluate_rules(info)
        assert any(m.category == ContextCategory.GENERATED for m in matches), (
            f"Failed for {gen_name}"
        )


def test_generated_header_comment_rule():
    sample = (
        "/*\n * Code generated by openapi-generator. DO NOT EDIT.\n */\n"
        "export interface Api..."
    )
    info = FileInfo(
        path="/project/src/api_client.ts",
        relative_path="src/api_client.ts",
        extension=".ts",
        size_bytes=3000,
        char_count=3000,
        line_count=80,
        estimated_tokens=750,
    )
    matches = evaluate_rules(info, sample)
    assert any(m.category == ContextCategory.GENERATED for m in matches)
    assert any(m.rule_id == "RULE_GENERATED_HEADER" for m in matches)


def test_minified_heuristic_rule():
    # Long single line
    long_line = "var a=1;" * 200  # 1600 chars on 1 line
    info = FileInfo(
        path="/project/assets/script.js",
        relative_path="assets/script.js",
        extension=".js",
        size_bytes=len(long_line),
        char_count=len(long_line),
        line_count=1,
        estimated_tokens=400,
    )
    matches = evaluate_rules(info, long_line)
    assert any(m.category == ContextCategory.MINIFIED for m in matches)


def test_large_data_file_rule():
    # Small json -> not flagged as large data
    small_info = FileInfo(
        path="/project/config.json",
        relative_path="config.json",
        extension=".json",
        size_bytes=2000,
        char_count=2000,
        line_count=50,
        estimated_tokens=500,
    )
    assert not any(m.category == ContextCategory.LARGE_DATA for m in evaluate_rules(small_info))

    # Large json (>50KB) -> flagged
    large_info = FileInfo(
        path="/project/dataset.json",
        relative_path="dataset.json",
        extension=".json",
        size_bytes=60 * 1024,
        char_count=60 * 1024,
        line_count=2000,
        estimated_tokens=15000,
    )
    assert any(m.category == ContextCategory.LARGE_DATA for m in evaluate_rules(large_info))


def test_log_file_rule():
    info = FileInfo(
        path="/project/logs/app.log",
        relative_path="logs/app.log",
        extension=".log",
        size_bytes=5000,
        char_count=5000,
        line_count=100,
        estimated_tokens=1250,
    )
    matches = evaluate_rules(info)
    assert any(m.category == ContextCategory.LOG_FILE for m in matches)


def test_large_token_file_rule():
    info = FileInfo(
        path="/project/docs/huge_manual.md",
        relative_path="docs/huge_manual.md",
        extension=".md",
        size_bytes=100_000,
        char_count=100_000,
        line_count=3000,
        estimated_tokens=25_000,  # Exceeds 20,000 threshold
    )
    matches = evaluate_rules(info)
    assert any(m.category == ContextCategory.LARGE_FILE for m in matches)
