"""End-to-end integration tests on realistic project structures."""

from __future__ import annotations

import json
from pathlib import Path

from context_audit.analyzer import AuditAnalyzer
from context_audit.cli import main


def create_sample_project(root: Path) -> None:
    """Create a realistic multi-language repository fixture."""
    # Source code
    src = root / "src" / "myapp"
    src.mkdir(parents=True)
    (src / "__init__.py").write_text('"""MyApp package."""\n', encoding="utf-8")
    (src / "service.py").write_text(
        "class Service:\n    def process(self, data):\n        return data.strip()\n" * 20,
        encoding="utf-8",
    )

    # Generated file
    generated = src / "generated"
    generated.mkdir()
    (generated / "api_client.py").write_text(
        "# Code generated by openapi-generator. DO NOT EDIT.\nclass ApiClient:\n    pass\n" * 15,
        encoding="utf-8",
    )

    # Documentation
    docs = root / "docs"
    docs.mkdir()
    (docs / "architecture.md").write_text(
        "# Architecture\n\nThis document describes system design...\n" * 40,
        encoding="utf-8",
    )

    # Lockfile
    (root / "package-lock.json").write_text(
        '{\n  "name": "myapp",\n  "lockfileVersion": 2\n}\n', encoding="utf-8"
    )

    # Duplicate file
    backup = root / "backup"
    backup.mkdir()
    (backup / "architecture_copy.md").write_text(
        "# Architecture\n\nThis document describes system design...\n" * 40,
        encoding="utf-8",
    )

    # Binary file
    (root / "logo.png").write_bytes(b"\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR")

    # .gitignore
    (root / ".gitignore").write_text("*.tmp\n", encoding="utf-8")
    (root / "temp.tmp").write_text("should be ignored", encoding="utf-8")


def test_full_integration_pipeline(tmp_path: Path):
    create_sample_project(tmp_path)

    analyzer = AuditAnalyzer(str(tmp_path))
    report = analyzer.analyze()

    assert report.files_scanned >= 6
    assert report.binary_files_skipped == 1
    assert report.total_estimated_tokens > 0

    # Ensure generated file and lockfile and duplicate are recognized as potentially unnecessary
    assert report.potentially_unnecessary_tokens > 0
    assert report.potential_useful_tokens > 0

    # Ensure duplicate is caught
    assert len(report.duplicate_groups) == 1
    dup = report.duplicate_groups[0]
    assert any("architecture.md" in f for f in dup.files)
    assert any("architecture_copy.md" in f for f in dup.files)

    # Check categories
    cat_names = {c.category for c in report.category_summaries}
    assert "generated" in cat_names
    assert "lockfile" in cat_names


def test_cli_integration_json(tmp_path: Path, capsys):
    create_sample_project(tmp_path)

    exit_code = main([str(tmp_path), "--json"])
    assert exit_code == 0

    captured = capsys.readouterr()
    data = json.loads(captured.out)

    assert data["project"] == str(tmp_path.resolve())
    assert data["binary_files_skipped"] == 1
    assert len(data["largest_files"]) > 0
    assert len(data["duplicates"]) == 1
