"""Deterministic rule detection for context-audit.

Analyzes file paths, names, extensions, and content to identify files that are
commonly unnecessary or wasteful for AI coding context.
"""

from __future__ import annotations

import fnmatch
import os
import re
from typing import TYPE_CHECKING

from context_audit.models import ContextCategory, RuleMatch

if TYPE_CHECKING:
    from context_audit.models import FileInfo

# Common lockfiles
LOCKFILE_NAMES: set[str] = {
    "package-lock.json",
    "yarn.lock",
    "pnpm-lock.yaml",
    "bun.lockb",
    "bun.lock",
    "poetry.lock",
    "cargo.lock",
    "composer.lock",
    "pipfile.lock",
    "go.sum",
    "gemfile.lock",
    "flake.lock",
    "mix.lock",
    "packages.lock.json",
    "npm-shrinkwrap.json",
    "pubspec.lock",
    "berksfile.lock",
}

# Vendor directory path components
VENDOR_DIR_PATTERNS: tuple[str, ...] = (
    "node_modules",
    "vendor",
    "third_party",
    "third-party",
    "pods",
    "bower_components",
    "jspm_packages",
    ".venv",
    "venv",
    "env",
    ".env",
    "site-packages",
)

# Build artifact / cache directory components
BUILD_DIR_PATTERNS: tuple[str, ...] = (
    "dist",
    "build",
    "target",
    "coverage",
    ".coverage",
    "htmlcov",
    "out",
    "bin",
    "obj",
    ".next",
    ".nuxt",
    ".turbo",
    ".parcel-cache",
    ".pytest_cache",
    ".mypy_cache",
    ".ruff_cache",
    ".cache",
    "__pycache__",
    ".gradle",
    ".docusaurus",
    ".svelte-kit",
    ".output",
    "storybook-static",
)

# Filename glob patterns for generated files
GENERATED_FILE_GLOBS: tuple[str, ...] = (
    "*.pb.go",
    "*.pb.cc",
    "*.pb.h",
    "*_pb2.py",
    "*_pb2_grpc.py",
    "*.generated.*",
    "*.g.dart",
    "*.freezed.dart",
    "*.designer.cs",
    "*.generated.cs",
    "*.gen.go",
    "*.min.js",
    "*.min.css",
    "*.bundle.js",
    "*.map",
    "*.d.ts.map",
    "*.js.map",
    "*.css.map",
    "moc_*.cpp",
    "qrc_*.cpp",
    "ui_*.h",
)

# Content patterns in header lines indicating generated code
GENERATED_HEADER_REGEX: re.Pattern[str] = re.compile(
    r"^\s*(?://|#|/\*|\*|--|<!--|;|\{-)\s*"
    r"(@generated|"
    r"code generated by|"
    r"auto-generated|"
    r"autogenerated|"
    r"do not edit|"
    r"do not modify|"
    r"this file was generated|"
    r"this file is generated|"
    r"automatically generated by|"
    r"swagger-codegen|"
    r"openapi-generator|"
    r"graphql code generator|"
    r"prisma generate|"
    r"wire:generate|"
    r"apollo:codegen)",
    re.IGNORECASE | re.MULTILINE,
)

# High token threshold for single files (default 20,000 tokens)
LARGE_FILE_TOKEN_THRESHOLD: int = 20_000

# Large data file byte threshold (50 KB for json/xml/csv/sql)
LARGE_DATA_BYTE_THRESHOLD: int = 50 * 1024


def evaluate_rules(file_info: FileInfo, content_sample: str = "") -> list[RuleMatch]:
    """Evaluate deterministic rules against a file to identify context issues.

    Args:
        file_info: FileInfo structure.
        content_sample: First chunk (e.g. 2KB to 4KB) of file content if available.

    Returns:
        List of RuleMatch objects.
    """
    matches: list[RuleMatch] = []
    rel_path = file_info.relative_path.replace("\\", "/")
    filename = os.path.basename(rel_path)
    lower_filename = filename.lower()
    path_parts = [p.lower() for p in rel_path.split("/")[:-1]]

    # 1. Vendor directory check
    for vendor_dir in VENDOR_DIR_PATTERNS:
        if vendor_dir in path_parts:
            matches.append(
                RuleMatch(
                    rule_id="RULE_VENDOR_DIR",
                    category=ContextCategory.VENDOR,
                    description=f"Under vendor/dependency directory '{vendor_dir}'",
                    is_unnecessary=True,
                )
            )
            break

    # 2. Build artifact / cache directory check
    for build_dir in BUILD_DIR_PATTERNS:
        if build_dir in path_parts:
            matches.append(
                RuleMatch(
                    rule_id="RULE_BUILD_DIR",
                    category=ContextCategory.BUILD_ARTIFACT,
                    description=f"Under build/cache/output directory '{build_dir}'",
                    is_unnecessary=True,
                )
            )
            break

    # 3. Lockfile check
    if lower_filename in LOCKFILE_NAMES:
        matches.append(
            RuleMatch(
                rule_id="RULE_LOCKFILE",
                category=ContextCategory.LOCKFILE,
                description=f"Dependency lockfile '{filename}'",
                is_unnecessary=True,
            )
        )

    # 4. Generated file name check
    for pattern in GENERATED_FILE_GLOBS:
        if fnmatch.fnmatch(lower_filename, pattern.lower()):
            matches.append(
                RuleMatch(
                    rule_id="RULE_GENERATED_FILENAME",
                    category=ContextCategory.GENERATED,
                    description=f"Filename matches generated pattern '{pattern}'",
                    is_unnecessary=True,
                )
            )
            break

    # 5. Generated code header check (from content sample, skipping documentation)
    doc_exts = {".md", ".markdown", ".rst", ".txt", ".adoc", ".license"}
    if content_sample and file_info.extension.lower() not in doc_exts:
        first_lines = "\n".join(content_sample.splitlines()[:50])
        if GENERATED_HEADER_REGEX.search(first_lines):
            # Avoid duplicate if already matched generated filename
            if not any(m.rule_id == "RULE_GENERATED_FILENAME" for m in matches):
                matches.append(
                    RuleMatch(
                        rule_id="RULE_GENERATED_HEADER",
                        category=ContextCategory.GENERATED,
                        description="Content header contains generated/do-not-edit marker",
                        is_unnecessary=True,
                    )
                )

    # 6. Minified file check
    if lower_filename.endswith((".min.js", ".min.css", ".min.svg", ".bundle.js")):
        if not any(m.category == ContextCategory.MINIFIED for m in matches):
            matches.append(
                RuleMatch(
                    rule_id="RULE_MINIFIED_EXT",
                    category=ContextCategory.MINIFIED,
                    description="Minified asset file",
                    is_unnecessary=True,
                )
            )
    elif file_info.line_count > 0 and file_info.char_count > 500:
        avg_line_length = file_info.char_count / file_info.line_count
        if avg_line_length > 250:
            matches.append(
                RuleMatch(
                    rule_id="RULE_MINIFIED_HEURISTIC",
                    category=ContextCategory.MINIFIED,
                    description=(
                        f"Suspected minified file (average line length {avg_line_length:.0f} chars)"
                    ),
                    is_unnecessary=True,
                )
            )

    # 7. Log files
    if file_info.extension.lower() in {".log", ".out"} or lower_filename.endswith(".log"):
        matches.append(
            RuleMatch(
                rule_id="RULE_LOG_FILE",
                category=ContextCategory.LOG_FILE,
                description="Log output file",
                is_unnecessary=True,
            )
        )

    # 8. Large data / dumps / test snapshots
    is_snapshot = (
        lower_filename.endswith((".snap", ".snapshot"))
        or "__snapshots__" in path_parts
        or "snapshots" in path_parts
    )
    if is_snapshot:
        matches.append(
            RuleMatch(
                rule_id="RULE_TEST_SNAPSHOT",
                category=ContextCategory.LARGE_DATA,
                description="Test snapshot file",
                is_unnecessary=True,
            )
        )
    elif file_info.extension.lower() in {
        ".json",
        ".xml",
        ".csv",
        ".tsv",
        ".sql",
        ".dump",
        ".sqlite",
        ".db",
    }:
        if file_info.size_bytes >= LARGE_DATA_BYTE_THRESHOLD:
            size_kb = file_info.size_bytes / 1024
            matches.append(
                RuleMatch(
                    rule_id="RULE_LARGE_DATA",
                    category=ContextCategory.LARGE_DATA,
                    description=f"Large data file ({size_kb:.1f} KB)",
                    is_unnecessary=True,
                )
            )

    # 9. Exceptionally large context file
    if file_info.estimated_tokens >= LARGE_FILE_TOKEN_THRESHOLD:
        matches.append(
            RuleMatch(
                rule_id="RULE_LARGE_TOKEN_COUNT",
                category=ContextCategory.LARGE_FILE,
                description=(
                    f"Exceeds {LARGE_FILE_TOKEN_THRESHOLD:,} estimated tokens "
                    f"({file_info.estimated_tokens:,} tokens)"
                ),
                is_unnecessary=True,
            )
        )

    return matches
